### ISSUE TITLE
Split package

### ISSUE THREAD

**Issue by Webkadabra** [jarrus90/yii2-currencies#2]
I'd love to use all the logic art (models, relations, console commands for updating etc.), but I'm not using any of *kartik-v* extensions in my app. Do you think we can split package into two? yii2-currencies-core and yii2-currencies-ui?

**Comment by jarrus90** [comment]
Hi, sorry for not answerring your request. I don`t support this packages for now, they stay only as dependencies for old projects. If you wish you are free to do anything to this code.
